export const property = {
  name: "Mount Echo",
  tagline: "Where intention meets elevation",
  description: "A curated hospitality property nestled in nature, designed for transformative week-long experiences. Four private bedrooms across two floors, shared common spaces built for connection, and the wild beauty of the outdoors just beyond the door.",
  location: {
    address: "Mount Echo Retreat",
    region: "Pacific Northwest",
    elevation: "2,400 ft",
    nearestAirport: "45 min drive",
    directions: "Detailed directions provided upon booking confirmation.",
  },
  floors: [
    {
      id: "floor-1",
      name: "Ground Floor",
      description: "Connected to the gardens and common spaces, the ground floor rooms offer easy flow between private rest and shared activity.",
      rooms: [
        {
          id: "f1-r1",
          name: "The Canopy Room",
          beds: "King",
          sqft: 320,
          description: "Floor-to-ceiling windows frame the tree canopy. Morning light filters through the leaves.",
          features: ["King bed", "En-suite bathroom", "Writing desk", "Garden view", "Heated floors"],
        },
        {
          id: "f1-r2",
          name: "The Creek Room",
          beds: "Queen",
          sqft: 280,
          description: "Fall asleep to the sound of the creek below. A grounding space designed for deep rest.",
          features: ["Queen bed", "En-suite bathroom", "Reading nook", "Creek view", "Blackout curtains"],
        },
      ],
    },
    {
      id: "floor-2",
      name: "Upper Floor",
      description: "Elevated views and extra privacy. The upper floor rooms sit above the treeline with panoramic mountain vistas.",
      rooms: [
        {
          id: "f2-r1",
          name: "The Summit Room",
          beds: "King",
          sqft: 340,
          description: "The highest point on the property. Wake up above the clouds with 180-degree mountain views.",
          features: ["King bed", "En-suite bathroom", "Private balcony", "Mountain view", "Soaking tub"],
        },
        {
          id: "f2-r2",
          name: "The Ridge Room",
          beds: "Queen",
          sqft: 290,
          description: "Perched along the ridge with views of the valley below. Warm wood and soft textiles throughout.",
          features: ["Queen bed", "En-suite bathroom", "Window seat", "Valley view", "Skylights"],
        },
      ],
    },
  ],
  commonAreas: [
    {
      id: "kitchen",
      name: "Chef's Kitchen",
      description: "Professional-grade kitchen with island seating for 8. Designed for communal cooking or private chef service.",
    },
    {
      id: "great-room",
      name: "The Great Room",
      description: "Double-height ceilings, stone fireplace, and modular furniture. Configurable for workshops, presentations, or evening gatherings.",
    },
    {
      id: "deck",
      name: "Wraparound Deck",
      description: "500 sq ft of covered outdoor space. Hot tub, fire pit, and views in every direction.",
    },
    {
      id: "studio",
      name: "The Studio",
      description: "A flexible space with natural light, whiteboards, and AV equipment. Perfect for focused work sessions or creative projects.",
    },
  ],
  amenities: [
    { id: "high-speed-wifi", name: "High-Speed WiFi", icon: "Wifi", category: "essentials" },
    { id: "chef-service", name: "Private Chef Available", icon: "ChefHat", category: "dining" },
    { id: "full-kitchen", name: "Full Kitchen", icon: "CookingPot", category: "dining" },
    { id: "hot-tub", name: "Hot Tub", icon: "Bath", category: "wellness" },
    { id: "fire-pit", name: "Outdoor Fire Pit", icon: "Flame", category: "outdoor" },
    { id: "hiking-trails", name: "Hiking Trails", icon: "Mountain", category: "outdoor" },
    { id: "meeting-room", name: "Meeting Space", icon: "Presentation", category: "work" },
    { id: "projector", name: "Projector & Screen", icon: "Monitor", category: "work" },
    { id: "whiteboard", name: "Whiteboards", icon: "PenTool", category: "work" },
    { id: "parking", name: "Free Parking", icon: "Car", category: "essentials" },
    { id: "ev-charger", name: "EV Charger", icon: "Zap", category: "essentials" },
    { id: "laundry", name: "Washer & Dryer", icon: "Shirt", category: "essentials" },
    { id: "sound-system", name: "Sound System", icon: "Music", category: "entertainment" },
    { id: "yoga-deck", name: "Yoga Deck", icon: "Heart", category: "wellness" },
    { id: "sauna", name: "Dry Sauna", icon: "Thermometer", category: "wellness" },
    { id: "bikes", name: "Mountain Bikes", icon: "Bike", category: "outdoor" },
  ],
  nearbyNature: [
    { name: "Echo Trail Loop", type: "hiking", distance: "0.2 mi", description: "A gentle 2-mile loop through old-growth forest, starting from the property." },
    { name: "Mirror Lake", type: "swimming", distance: "0.5 mi", description: "A pristine alpine lake perfect for morning cold plunges or afternoon swims." },
    { name: "Ridgeline Overlook", type: "hiking", distance: "1.2 mi", description: "A moderate climb rewarded with panoramic views of the valley and surrounding peaks." },
    { name: "Cedar Creek", type: "fishing", distance: "0.1 mi", description: "Runs along the property boundary. Seasonal trout fishing with permit." },
  ],
};
