export const claudeCampTheme = {
  slug: "claude-camp",
  name: "Claude Camp",
  tagline: "MVP to traction in 5 days.",
  colors: {
    primary: "#0D0D0D",
    secondary: "#E07B39",
    accent: "#E07B39",
    background: "#F8F5F0",
    surface: "#FFFFFF",
    text: "#0D0D0D",
    textMuted: "#6B6B6B",
    heroBg: "#0D0D0D",
    heroText: "#FAFAFA",
  },
  copy: {
    heroHeadline: "From Idea\nto Traction.",
    heroSubheadline: "A week-long AI-powered founder intensive at Mount Echo. Build your product, sharpen your GTM, and ship — with Claude as your co-pilot.",
    introTitle: "What is Claude Camp?",
    introBody: "Claude Camp is a 5-day intensive for founders and builders who are ready to move fast. Bring your MVP, your questions, and your ambition. Leave with traction, a sharpened GTM strategy, and the AI workflows that will define how you build from here. Small cohort. Real stakes. Everything built live.",
    ctaText: "Apply for Claude Camp",
  },
  highlights: [
    {
      icon: "Zap",
      title: "Build with Claude",
      description: "Use Claude as your co-pilot for code, copy, strategy, and every decision in between. We provide API access — you provide the vision.",
    },
    {
      icon: "Target",
      title: "GTM Sprint",
      description: "Go from 'we have a product' to 'we have customers' with structured workshops, positioning sprints, and real-time peer feedback.",
    },
    {
      icon: "Users",
      title: "Cohort of Builders",
      description: "6–8 founders in the same room for a week. Deliberately small. The connections and cross-pollination alone are worth the trip.",
    },
    {
      icon: "Rocket",
      title: "Ship Before You Leave",
      description: "The goal isn't a deck or a plan. It's something live — in users' hands, with early signal — before checkout on Friday afternoon.",
    },
  ],
  itinerary: [
    {
      day: "Monday",
      title: "Arrive & Define",
      items: [
        "Check-in, workspace setup, cohort intros",
        "Product clarity workshop: what problem, for whom, why now",
        "Define your personal week-one goal",
        "Claude tooling setup + workflow audit",
        "Dinner + lightning demos from each founder",
      ],
    },
    {
      day: "Tuesday",
      title: "Build",
      items: [
        "Morning: GTM hypothesis — target, channel, message",
        "Claude-assisted build sprint (code, copy, or both)",
        "Lunch + 1:1 feedback sessions",
        "Afternoon: Landing page + positioning with Claude",
        "Evening: Peer review & critique sessions",
      ],
    },
    {
      day: "Wednesday",
      title: "Validate",
      items: [
        "Morning: User research sprint — 3 conversations before noon",
        "Claude-assisted outreach copy & cold email",
        "Afternoon: Synthesize feedback, update positioning",
        "Hike to Mirror Lake — debrief in the wild",
        "Dinner: Pivot or persist decision for each founder",
      ],
    },
    {
      day: "Thursday",
      title: "Distribution",
      items: [
        "Morning: Build the acquisition channel (SEO, community, outbound)",
        "Claude-assisted content & distribution with AI",
        "Afternoon: Pitch deck sprint (15 slides, 10 minutes)",
        "Evening: Demo prep, investor Q&A simulation",
      ],
    },
    {
      day: "Friday",
      title: "Ship & Debrief",
      items: [
        "Demo Day — each founder presents live progress",
        "Final product push: launch or milestone shipped",
        "30-day GTM plan built with Claude",
        "Brunch + checkout by noon",
      ],
    },
  ],
  featuredAmenities: [
    "high-speed-wifi",
    "meeting-room",
    "whiteboard",
    "chef-service",
    "projector",
    "sound-system",
  ],
  pricing: {
    headline: "Your Traction Investment",
    startingAt: "$5,500",
    unit: "per founder · per week",
    includes: [
      "Private bedroom for the full week",
      "All meals — breakfast, lunch, dinner",
      "High-speed dedicated internet",
      "Claude API access provided",
      "Facilitated workshops + daily 1:1 coaching",
      "30-day post-camp follow-up check-in",
    ],
  },
};
